
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.Fixed fixed1;

	private global::Gtk.Label helloLabel;

	private global::Gtk.Label currentLocationText;

	private global::Gtk.Label currentLocationAddress;

	private global::Gtk.Label dateText;

	private global::Gtk.Label currentTimeText;

	private global::Gtk.ComboBox startBox;

	private global::Gtk.ComboBox destinationBox;

	private global::Gtk.Label startAtText;

	private global::Gtk.Label destinationText;

	private global::Gtk.Label startAtTextNote;

	protected virtual void Build()
	{
		global::Stetic.Gui.Initialize(this);
		// Widget MainWindow
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString("MainWindow");
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		this.BorderWidth = ((uint)(3));
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.fixed1 = new global::Gtk.Fixed();
		this.fixed1.HasWindow = false;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.helloLabel = new global::Gtk.Label();
		this.helloLabel.Name = "helloLabel";
		this.helloLabel.LabelProp = global::Mono.Unix.Catalog.GetString("Hello, User!");
		this.fixed1.Add(this.helloLabel);
		global::Gtk.Fixed.FixedChild w1 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.helloLabel]));
		w1.X = 20;
		w1.Y = 20;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.currentLocationText = new global::Gtk.Label();
		this.currentLocationText.Name = "currentLocationText";
		this.currentLocationText.LabelProp = global::Mono.Unix.Catalog.GetString("Your address:");
		this.fixed1.Add(this.currentLocationText);
		global::Gtk.Fixed.FixedChild w2 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.currentLocationText]));
		w2.X = 20;
		w2.Y = 50;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.currentLocationAddress = new global::Gtk.Label();
		this.currentLocationAddress.Name = "currentLocationAddress";
		this.currentLocationAddress.LabelProp = global::Mono.Unix.Catalog.GetString("Address here");
		this.fixed1.Add(this.currentLocationAddress);
		global::Gtk.Fixed.FixedChild w3 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.currentLocationAddress]));
		w3.X = 20;
		w3.Y = 70;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.dateText = new global::Gtk.Label();
		this.dateText.Name = "dateText";
		this.dateText.LabelProp = global::Mono.Unix.Catalog.GetString("Date here");
		this.fixed1.Add(this.dateText);
		global::Gtk.Fixed.FixedChild w4 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.dateText]));
		w4.X = 600;
		w4.Y = 20;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.currentTimeText = new global::Gtk.Label();
		this.currentTimeText.Name = "currentTimeText";
		this.currentTimeText.LabelProp = global::Mono.Unix.Catalog.GetString("Time here");
		this.fixed1.Add(this.currentTimeText);
		global::Gtk.Fixed.FixedChild w5 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.currentTimeText]));
		w5.X = 620;
		w5.Y = 45;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.startBox = global::Gtk.ComboBox.NewText();
		this.startBox.Name = "startBox";
		this.fixed1.Add(this.startBox);
		global::Gtk.Fixed.FixedChild w6 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.startBox]));
		w6.X = 20;
		w6.Y = 155;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.destinationBox = global::Gtk.ComboBox.NewText();
		this.destinationBox.Name = "destinationBox";
		this.fixed1.Add(this.destinationBox);
		global::Gtk.Fixed.FixedChild w7 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.destinationBox]));
		w7.X = 20;
		w7.Y = 235;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.startAtText = new global::Gtk.Label();
		this.startAtText.Name = "startAtText";
		this.startAtText.LabelProp = global::Mono.Unix.Catalog.GetString("Start at text");
		this.fixed1.Add(this.startAtText);
		global::Gtk.Fixed.FixedChild w8 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.startAtText]));
		w8.X = 20;
		w8.Y = 135;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.destinationText = new global::Gtk.Label();
		this.destinationText.Name = "destinationText";
		this.destinationText.LabelProp = global::Mono.Unix.Catalog.GetString("Destination text");
		this.fixed1.Add(this.destinationText);
		global::Gtk.Fixed.FixedChild w9 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.destinationText]));
		w9.X = 20;
		w9.Y = 215;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.startAtTextNote = new global::Gtk.Label();
		this.startAtTextNote.Name = "startAtTextNote";
		this.startAtTextNote.LabelProp = global::Mono.Unix.Catalog.GetString("note here");
		this.fixed1.Add(this.startAtTextNote);
		global::Gtk.Fixed.FixedChild w10 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.startAtTextNote]));
		w10.X = 100;
		w10.Y = 132;
		this.Add(this.fixed1);
		if ((this.Child != null))
		{
			this.Child.ShowAll();
		}
		this.DefaultWidth = 772;
		this.DefaultHeight = 488;
		this.Show();
	}
}
